### ISSUE TITLE
Update endpoint

### ISSUE THREAD

**Issue by hronix** [microsoft/bing-search-sdk-for-python#6]
https://github.com/microsoft/bing-search-sdk-for-python/blob/f9a60d68f5287a657e9e71aa0ba05a46b4dda257/samples/rest/BingImageSearchV7.py#L18

bing/ should be removed from endpoint

**Comment by bbernicker** [comment]
Just bumping this. It is still an issue in the sample code.

**Comment by GhiathAjam** [comment]
Should be fixed now, please re-open / comment here if you can reproduce.
